name: "My-workflow"
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Cloning"
      - run: ls -l
        name: "checking the file system with clone"

  deploy:
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        name: This is just an echo command
      - run: ls -l
        name: "checking the file system without clone"
