name: "My-workflow"
on:
  pull_request:
    branches:
      - "main"
env:
  AWS_REGION: aws-region

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Cloning"

      - name: Caching the modules
        id: modules
        uses: actions/cache@v3
        with:
          path: venv
          key: pip1-cache-${{ hashFiles('requirements.txt')}}

      - name: Installing PIP
        if: steps.modules.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest==7.4.2 flake8==6.0.0

      - name: "Static testing with Flake8"
        run: |
          source venv/bin/activate
          flake8 app.py bmi.py emi.py test_bmi.py

      - name: "Functionality Testing with Pytest"
        run: |
          source venv/bin/activate
          pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        name: This is just an echo command
      - run: ls -l
        name: "checking the file system without clone"

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Download Repo"

      - name: Configuring AWS
        id: aws_info
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: get account id
        run: echo "${{ steps.aws_info.outputs.aws-account-id }}"

      - name: list-cluster
        run: aws ecs list-clusters
