name: "My-workflow"
on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Cloning"
      - run: python3 --version
      - name: "install packages"
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: "Testing with Pytest"
        run: pytest

  deploy:
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        name: This is just an echo command
      - run: ls -l
        name: "checking the file system without clone"
