name: "My-workflow"
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Cloning"
      - run: python3 --version
      - name: "install packages"
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: "Testing with Pytest"
        run: pytest

  deploy:
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        name: This is just an echo command
      - run: ls -l
        name: "checking the file system without clone"
